/* -*- mode: c; c-basic-offset: 2; indent-tabs-mode: nil; -*-
 * DO NOT EDIT; autogenerated by http://github.com/hzeller/bdfont.data
 * Font-File: smalltext.bdf
 *      Font: -Misc-Fixed-Medium-R-Normal--18-120-100-100-C-90-ISO10646-1
 *      Size: 18   Baseline at: 11
 * For chars: .0123456789-Please zero on flat surface mm>sag=≈"©Henner Zeller/ƒ±⌀▂⯊
 */

#include "font-smalltext.h"

static const uint8_t PROGMEM _font_data_smalltext[] = {
  /* codepoint ' ' plain bytes */

  /* codepoint '"' plain bytes */
  0x0f,0x00,0x00,0x0f,

  /* codepoint '-' RLE/nibble */
  0x07,0x40,

  /* codepoint '.' plain bytes */
  0x06,0x06,

  /* codepoint '/' RLE/4 */
  0x56,0x00,0x80,0x60,0x10,  0x05,0x0c,0x02,
  0xb5,0x04,0x03,0x00,0x00,

  /* codepoint '0' plain bytes */
  0xf8,0x04,0x02,0x02,0x02,0x04,0xf8,
  0x01,0x02,0x04,0x04,0x04,0x02,0x01,

  /* codepoint '1' RLE/4 */
  0x55,0x10,0x08,0x04,0xfe,  0x03,0x00,
  0x37,0x04,0x07,0x04,

  /* codepoint '2' plain bytes */
  0x08,0x04,0x02,0x82,0x42,0x24,0x18,
  0x04,0x06,0x05,0x04,0x04,0x04,0x04,

  /* codepoint '3' plain bytes */
  0x02,0x02,0x02,0x22,0x32,0x4a,0x86,
  0x02,0x04,0x04,0x04,0x04,0x02,0x01,

  /* codepoint '4' plain bytes */
  0xc0,0xa0,0x90,0x88,0x84,0xfe,0x80,
  0x00,0x00,0x00,0x00,0x00,0x07,0x00,

  /* codepoint '5' RLE/nibble */
  0x41,0x3e,0x22,  0x11,0x42,0x82,
  0x41,0x02,0x04,  0x11,0x02,0x01,

  /* codepoint '6' plain bytes */
  0xf8,0x44,0x22,0x22,0x22,0x42,0x80,
  0x01,0x02,0x04,0x04,0x04,0x02,0x01,

  /* codepoint '7' RLE/4 */
  0x57,0x02,0x82,0x62,0x1a,  0x01,0x06,
  0x37,0x00,0x07,0x00,

  /* codepoint '8' plain bytes */
  0x88,0x54,0x22,0x22,0x22,0x54,0x88,
  0x01,0x02,0x04,0x04,0x04,0x02,0x01,

  /* codepoint '9' plain bytes */
  0x18,0x24,0x42,0x42,0x42,0x24,0xf8,
  0x00,0x04,0x04,0x04,0x04,0x02,0x01,

  /* codepoint '=' RLE/nibble */
  0x07,0x20,
  0x07,0x01,

  /* codepoint '>' plain bytes */
  0x04,0x08,0x10,0xa0,0x40,
  0x04,0x02,0x01,0x00,0x00,

  /* codepoint 'H' RLE/nibble */
  0x51,0xfe,0x20,  0x01,0xfe,
  0x51,0x07,0x00,  0x01,0x07,

  /* codepoint 'P' RLE/nibble */
  0x41,0xfe,0x42,  0x11,0x24,0x18,
  0x61,0x07,0x00,

  /* codepoint 'Z' RLE/4 */
  0x55,0x02,0x82,0x42,0x22,  0x15,0x12,0x0a,0x06,
  0x3d,0x07,0x04,0x04,

  /* codepoint 'a' RLE/nibble */
  0x51,0x00,0x90,  0x01,0xe0,
  0x41,0x03,0x04,  0x11,0x02,0x07,

  /* codepoint 'c' RLE/nibble */
  0x51,0xe0,0x10,  0x01,0x20,
  0x51,0x03,0x04,  0x01,0x02,

  /* codepoint 'e' RLE/nibble */
  0x51,0xe0,0x90,  0x01,0xe0,
  0x51,0x03,0x04,  0x01,0x02,

  /* codepoint 'f' RLE/4 */
  0x66,0x40,0xfc,0x42,0x02,  0x01,0x0c,
  0x76,0x00,0x07,0x00,0x00,

  /* codepoint 'g' RLE/nibble */
  0x41,0xe0,0x10,  0x11,0xe0,0x10,
  0x41,0x1a,0x25,  0x11,0x24,0x18,

  /* codepoint 'l' RLE/4 */
  0x26,0x02,0xfe,0x00,
  0x26,0x04,0x07,0x04,

  /* codepoint 'm' plain bytes */
  0xf0,0x10,0x10,0xe0,0x10,0x10,0xe0,
  0x07,0x00,0x00,0x03,0x00,0x00,0x07,

  /* codepoint 'n' RLE/nibble */
  0x11,0xf0,0x20,  0x14,0x10,0xe0,
  0x51,0x07,0x00,  0x01,0x07,

  /* codepoint 'o' RLE/nibble */
  0x51,0xe0,0x10,  0x01,0xe0,
  0x51,0x03,0x04,  0x01,0x03,

  /* codepoint 'r' RLE/4 */
  0xd5,0x10,0xe0,0x20,0x10,  0x01,0x60,
  0xb5,0x00,0x07,0x00,0x00,

  /* codepoint 's' RLE/nibble */
  0x51,0x60,0x90,  0x01,0x20,
  0x51,0x02,0x04,  0x01,0x03,

  /* codepoint 't' RLE/4 */
  0x76,0x10,0xfc,0x10,0x00,
  0x76,0x00,0x03,0x04,0x02,

  /* codepoint 'u' RLE/nibble */
  0x51,0xf0,0x00,  0x01,0xf0,
  0x41,0x03,0x04,  0x11,0x02,0x07,

  /* codepoint 'z' plain bytes */
  0x10,0x10,0x10,0x90,0x50,0x30,0x10,
  0x04,0x06,0x05,0x04,0x04,0x04,0x04,

  /* codepoint U+00a9 plain bytes */
  0xf8,0x04,0x72,0x8a,0x8a,0x52,0x04,0xf8,
  0x00,0x01,0x02,0x02,0x02,0x02,0x01,0x00,

  /* codepoint U+00b1 RLE/nibble */
  0x13,0x10,0xfe,  0x03,0x10,
  0x07,0x02,

  /* codepoint U+0192 RLE/4 */
  0x99,0x00,0x40,0xfc,0x42,  0x01,0x04,
  0xd9,0x08,0x10,0x0f,0x00,

  /* codepoint U+2248 plain bytes */
  0x20,0x90,0x90,0x20,0x40,0x40,0x20,
  0x01,0x00,0x00,0x01,0x02,0x02,0x01,

  /* codepoint U+2300 plain bytes */
  0xc0,0x20,0x10,0x90,0x50,0x20,0xd0,
  0x05,0x02,0x05,0x04,0x04,0x02,0x01,

  /* codepoint U+2582 RLE/nibble */
  0x11,0x60,0x50,  0x31,0x48,0x44,  0x11,0x24,0x14,  0x01,0x0c,
  0x09,0x18,

  /* codepoint U+2bca RLE/4 */
  0xdd,0x00,0x02,0x7e,0x02,  0x01,0x00,
  0xb9,0x18,0x1c,0x1e,0x1c,  0x01,0x18,
};

static const struct GlyphData PROGMEM _font_glyphs_smalltext[] = {
  {.codepoint = ' ',    .width= 9, .stripe_begin=1, .stripe_end=0, .left_margin=0, .right_margin=0, BDFONT_PLAIN(0), .data_offset=   0},
  {.codepoint = '"',    .width= 9, .stripe_begin=0, .stripe_end=1, .left_margin=3, .right_margin=2, BDFONT_PLAIN(0), .data_offset=   0},
  {.codepoint = '-',    .width= 9, .stripe_begin=0, .stripe_end=1, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset=   4},
  {.codepoint = '.',    .width= 9, .stripe_begin=1, .stripe_end=2, .left_margin=4, .right_margin=3, BDFONT_PLAIN(0), .data_offset=   6},
  {.codepoint = '/',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset=   8},
  {.codepoint = '0',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  21},
  {.codepoint = '1',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset=  35},
  {.codepoint = '2',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  46},
  {.codepoint = '3',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  60},
  {.codepoint = '4',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset=  74},
  {.codepoint = '5',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset=  88},
  {.codepoint = '6',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 100},
  {.codepoint = '7',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 114},
  {.codepoint = '8',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 125},
  {.codepoint = '9',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 139},
  {.codepoint = '=',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 153},
  {.codepoint = '>',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_PLAIN(0), .data_offset= 157},
  {.codepoint = 'H',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 167},
  {.codepoint = 'P',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 177},
  {.codepoint = 'Z',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 186},
  {.codepoint = 'a',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 199},
  {.codepoint = 'c',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 210},
  {.codepoint = 'e',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 220},
  {.codepoint = 'f',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 230},
  {.codepoint = 'g',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 242},
  {.codepoint = 'l',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=2, .right_margin=2, BDFONT_RLE(2)  , .data_offset= 254},
  {.codepoint = 'm',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 262},
  {.codepoint = 'n',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 276},
  {.codepoint = 'o',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 287},
  {.codepoint = 'r',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 297},
  {.codepoint = 's',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 309},
  {.codepoint = 't',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 319},
  {.codepoint = 'u',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 329},
  {.codepoint = 'z',    .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 340},
  {.codepoint = 0x00a9, .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 354},
  {.codepoint = 0x00b1, .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(1)  , .data_offset= 370},
  {.codepoint = 0x0192, .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_RLE(2)  , .data_offset= 377},
  {.codepoint = 0x2248, .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 389},
  {.codepoint = 0x2300, .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=1, .right_margin=1, BDFONT_PLAIN(0), .data_offset= 403},
  {.codepoint = 0x2582, .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=0, BDFONT_RLE(1)  , .data_offset= 417},
  {.codepoint = 0x2bca, .width= 9, .stripe_begin=0, .stripe_end=2, .left_margin=0, .right_margin=0, BDFONT_RLE(2)  , .data_offset= 430},
};

const struct FontData PROGMEM font_smalltext = {
  .available_glyphs = 41,
  .baseline = 11,
  .stripes = 2,
  .bits = _font_data_smalltext,
  .glyphs = _font_glyphs_smalltext
};
