// -*- mode: c++; c-basic-offset: 2; indent-tabs-mode: nil; -*-
// This is autogenerated.
#ifndef FONT_SMALLTEXT_
#define FONT_SMALLTEXT_

#include "font-support.h"
#include <avr/pgmspace.h>

struct ProgmemFont_smalltext_t {
  struct MetaFont meta;
  struct {
    struct MetaGlyph meta;
    uint8_t data[2][8];  // page-stripes, width
  } glyphs[24];
} __attribute__((packed));

extern const struct ProgmemFont_smalltext_t PROGMEM progmem_font_smalltext;

#endif // FONT_SMALLTEXT_
