// -*- mode: c++; c-basic-offset: 2; indent-tabs-mode: nil; -*-
// This is autogenerated.
#ifndef FONT_tinytext_
#define FONT_tinytext_

#include "font-support.h"
#include <avr/pgmspace.h>

struct ProgmemFont_tinytext_t {
  struct MetaFont meta;
  struct {
    struct MetaGlyph meta;
    uint8_t data[2][7];  // page-stripes, width
  } glyphs[27];
} __attribute__((packed));

extern const struct ProgmemFont_tinytext_t PROGMEM progmem_font_tinytext;

#endif // FONT_tinytext_
