// -*- mode: c++; c-basic-offset: 2; indent-tabs-mode: nil; -*-
// This is autogenerated.
#ifndef FONT_smalltext_
#define FONT_smalltext_

#include "font-support.h"
#include <avr/pgmspace.h>

struct ProgmemFont_smalltext_t {
  struct MetaFont meta;
  struct {
    struct MetaGlyph meta;
    uint8_t data[2][8];  // page-stripes, width
  } glyphs[37];
} __attribute__((packed));

extern const struct ProgmemFont_smalltext_t PROGMEM progmem_font_smalltext;
#define font_smalltext (&progmem_font_smalltext.meta)

#endif // FONT_smalltext_
