// -*- mode: c++; c-basic-offset: 2; indent-tabs-mode: nil; -*-
// This is autogenerated.
#ifndef FONT_bignumber_
#define FONT_bignumber_

#include "font-support.h"
#include <avr/pgmspace.h>

struct ProgmemFont_bignumber_t {
  struct MetaFont meta;
  struct {
    struct MetaGlyph meta;
    uint8_t data[5][35];  // page-stripes, width
  } glyphs[15];
} __attribute__((packed));

extern const struct ProgmemFont_bignumber_t PROGMEM progmem_font_bignumber;

#endif // FONT_bignumber_
